import Head from 'next/head';
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

import Footer from "./Footer";
import Header from "./Header";

export default function Layout({ title, desc, className, children }) {
    return (
    <>
        <Head>
            <title>{title? title + ' | Arizona' : 'Arizona'}</title>
            <meta name="description" content={desc? desc : 'Generated by create next app'} />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <ToastContainer position='bottom-center' limit={1} />
            <Header />
            <main className={`grow ${className}`}>{children}</main>
            <Footer />
    </>
    )
  }
  